### ISSUE TITLE
Braintree integration in yii2

### ISSUE THREAD

**Issue by dubeymahi48** [tuyakhov/yii2-braintree#1]
Hi Dear, 

I need to implement the Braintree in yii2, Please suggest if this is working?
I checked issues tab but there is no issue. 

Please provide setup details also. Thanks in advance.

**Comment by tuyakhov** [comment]
Yes it is working, i have few projects that uses this extension. Just was not updated for a long time. I will provide setup details on Readme file later. All you need to declare Braintree as component in config. And You also can use form widgets, and model(BraintreeForm) which will validate all purchase information.

**Comment by dubeymahi48** [comment]
Thank you for quick reply.
Please also add the composer command.

**Comment by DDholiyan** [comment]
Hi tuyakhov,

Hope you are doing well!

please provide composer command and  configuration/uses steps.

Thanks in advance.

**Comment by DDholiyan** [comment]
Hi tuyakhov,

Hope you are doing well!

please provide composer command and  configuration/uses steps.

Thanks in advance.

**Comment by DDholiyan** [comment]
Hi tuyakhov,

Hope you are doing well!

please provide composer command and  configuration/uses steps.

Thanks in advance.

**Comment by talofo** [comment]
Hello. We are looking for this as well. Care to provide some details, so we can build with it? 

Thank you

**Comment by alesr** [comment]
Hi tuyakhov, i appreciate your effort on this project but would be nice to have some documentation about how to implement that.

Thanks in advance.

**Comment by tuyakhov** [comment]
Ok, guys. I will provide all necessary documentation, and tests for this extension during this week. Thanks a lot for your attention, and sorry for delay.

**Comment by alesr** [comment]
Cheers! =D

**Comment by DDholiyan** [comment]
HI tuyakhov,

I found below error during installation, please check and correct.

Problem 1
- The requested package tuyakhov/yii2-braintree could not be found in any version, there 

otential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stabilit
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more detai

ead https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by talofo** [comment]
DDoholiyan, I may be able to help. What command are you trying to run? Care to share please?

Can you share your composer.json as well? 

Thank you.

**Comment by tuyakhov** [comment]
Everything is ok. Because i still dont have stable release. Only dev-master is available right now. After i will finish with docs i will make a release. Of Course you can use current version by adding 

```
"tuyahov/yii2-braintree" : "dev-master"
```

 into your `composer.json` file, but i don't recommend to do that, because i also will make some changes in code.

**Comment by DDholiyan** [comment]
Hi talofo and tuyakhov,

I am waiting for coding changes. please also update the readme text file in way that this will help in the implementation. please also tell me when this will be update.

@talofo, I will share you my composer.json after the changes of Tuyakhov if the solution will not work

Thanks in advance.

**Comment by tuyakhov** [comment]
@DDholiyan I will finish everything at the end this week.

**Comment by DDholiyan** [comment]
Thank you tuyakhov.

**Comment by tuyakhov** [comment]
Hi guys, i have finished small updates. It would be nice if you will send me some feedback or PR.

**Comment by DDholiyan** [comment]
Hi tuyakhov,

Thanks for your hard work.

I am looking for curl file, Because I need to pay from my site means i don't want to go on braintree for payment.

Please reply asap.

Thanks
DDholiyan

**Comment by DDholiyan** [comment]
please see the below core php link this may help to you.
http://www.hurricanesoftwares.com/integrating-braintree-payment-gateway-with-php/

I post this link ony because there are solution that I want recurring payment etc.

**Comment by tuyakhov** [comment]
This is exactly that was implemented here. You just need to follow instructions, customers don't need to go on braintree for payment. please see [Readme](https://github.com/tuyakhov/yii2-braintree/blob/master/README.md)

**Comment by DDholiyan** [comment]
Thanks tuyakhov, I will check now.

**Comment by masoud91** [comment]
Hi ,
using `php composer.phar require --prefer-dist tuyakhov/yii2-braintree "*"`
I face this errors :

```
Problem 1
    - tuyakhov/yii2-braintree 1.0.2 requires npm-asset/braintree-web 2.10.* -> no matching package found.
    - tuyakhov/yii2-braintree 1.0.1 requires npm-asset/braintree-web 2.10.* -> no matching package found.
    - Installation request for tuyakhov/yii2-braintree ^1.0 -> satisfiable by tuyakhov/yii2-braintree[1.0.1, 1.0.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
```

would you please guide me ?

**Comment by tuyakhov** [comment]
Works fine for me. Could you please provide me full `composer.json` file

**Comment by masoud91** [comment]
Thanks for your quick answer , this is my composer.json

```
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Application Template",
    "keywords": ["yii2", "framework", "advanced", "application template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "rmrevin/yii2-fontawesome": "2.10.*",
    "yiisoft/yii2-jui": "~2.0.0",
     "metalguardian/yii2-fotorama-widget": "*",
        "romdim/yii2-bootstrap-material": "dev-master",
    "wiisoft/yii2-materialize": "*",
        "kartik-v/yii2-grid": "@dev",
        "tuyakhov/yii2-braintree": "*"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*",
        "yiisoft/yii2-authclient": "~2.0.0"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
```

**Comment by tuyakhov** [comment]
Sorry i can't reproduce it. Your `composer.json` works just fine for me. Looks like it is something generic and not related with library.

**Comment by tuyakhov** [comment]
Your issue could be related with https://github.com/francoispluchino/composer-asset-plugin/issues/198

**Comment by tuyakhov** [comment]
Issue I got ![](http://i.imgur.com/Mt04s41.png)

**Comment by dmitry-kulikov** [comment]
@masoud91 make sure you have installed fxp/composer-asset-plugin and it is not too old. Looks similar to #6 . After that you will encounter issue which @tuyakhov described above.

**Comment by masoud91** [comment]
@tuyakhov @dmitry-kulikov 
Thanks a lot , I will check it .
