### ISSUE TITLE
Error when get lib by composer 

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [tuyakhov/yii2-braintree#2]
I tried to get this extantoin by using 
php composer.phar require --prefer-dist tuyakhov/yii2-braintree "*"
and get error like that:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tuyakhov/yii2-braintree could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

What I did wrong ? I will confess that I am not good at using composer

**Comment by tuyakhov** [comment]
Thanks. Fixed. Try now
